import {AppProvider} from "@/components/AppContext";
import Header from "@/components/layout/Header";
import { Roboto_Condensed } from 'next/font/google'
import './globals.css'
import {Toaster} from "react-hot-toast";

const roboto = Roboto_Condensed({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
        <main className="max-w-4xl mx-auto p-4">
          <AppProvider>
            <Toaster />
            <Header />
            {children}
            <footer className="border-t p-8 text-center text-gray-500 mt-16">
              Amalia Y. Panane &copy; 2023 
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  )
}
